List cat1 = [
  {"item_name": "Radha Krishna Wall Hanging |Radha Krishna Jhula Wall Hanging for Home Decor", "item_url": "https://m.media-amazon.com/images/I/71TmSRkmAEL._AC_UL320_ML3_.jpg", "item_price": "799"},
  {"item_name": "Fabzone Brown Antique Look Lord Ganesha God OM Ganesh Ganpati Idol Statue Wall Hanging Showpiece Figurine", "item_url": "https://m.media-amazon.com/images/I/71d8VOc22PL._AC_UL320_ML3_.jpg", "item_price": "599"},
  {"item_name": "Crafthut Handmade Brass Material Statue of Lord Radha Krishna Seating on Jhoola/Swing", "item_url": "https://m.media-amazon.com/images/I/71rHTeqk2AL._AC_UL320_ML3_.jpg", "item_price": "1,499"},
  {"item_name": "ISKCON Jagannath JAAP MALA for Pooja-Astrology-108+1 Beads and Certified Small Size", "item_url": "https://m.media-amazon.com/images/I/41XLJJ9XKsL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath Tulsi Bead Triple Layer Kanthi Mala for Neck", "item_url": "https://m.media-amazon.com/images/I/91qX4o7A5lL._AC_UL320_ML3_.jpg", "item_price": "198"},
  {"item_name": "KRISHNA:Devadi_Devudu Sri Krishna Bhagavanudu (Hardcover, Telugu, His Divine Grace A.C. Bhaktivedanta Swami Prabhupada)", "item_url": "https://m.media-amazon.com/images/I/513sosXGijL._AC_UL320_ML3_.jpg", "item_price": "349"},
  {"item_name": "In Vaikuntha Not Even The Leaves Fall: A Treatise On The Bondage Of The Jiva", "item_url": "https://m.media-amazon.com/images/I/71nyvDru6EL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Arcana, Volume 2: The ISKCON Deity Worship Journal", "item_url": "https://m.media-amazon.com/images/I/81jNGxJW9YL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Original Bhagavad Gita (Small Size) \u2014 Dual Color Print", "item_url": "https://m.media-amazon.com/images/I/81FC5v9M0jL._AC_UL320_ML3_.jpg", "item_price": "399"},
  {"item_name": "Radha Krishna Wall Hanging |Radha Krishna Jhula Wall Hanging for Home Decor", "item_url": "https://m.media-amazon.com/images/I/71TmSRkmAEL._AC_UL320_ML3_.jpg", "item_price": "799"},
  {"item_name": "Fabzone Brown Antique Look Lord Ganesha God OM Ganesh Ganpati Idol Statue Wall Hanging Showpiece Figurine", "item_url": "https://m.media-amazon.com/images/I/71d8VOc22PL._AC_UL320_ML3_.jpg", "item_price": "599"},
  {"item_name": "Crafthut Handmade Brass Material Statue of Lord Radha Krishna Seating on Jhoola/Swing", "item_url": "https://m.media-amazon.com/images/I/71rHTeqk2AL._AC_UL320_ML3_.jpg", "item_price": "1,499"},
  {"item_name": "The Gita", "item_url": "https://m.media-amazon.com/images/I/61NJ0cIFsfL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "ISKCON Jagannath Dashavatara Fine Art Paper Print Poster", "item_url": "https://m.media-amazon.com/images/I/612AqGdJ+2L._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath Metal Lord Shree Krishna Pendant for Men and Women", "item_url": "https://m.media-amazon.com/images/I/518CSiugatL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Prabhupada: Messenger of the Supreme Lord [Biography of Srila Prabhupada, the founder Acarya of ISKCON]", "item_url": "https://m.media-amazon.com/images/I/51pjwZedJ4L._AC_UL320_ML3_.jpg", "item_price": "130"},
  {"item_name": "Lord krishna's 46 in 1 Gayatri Mantra Hare Krishna (Iskcon Voice) Mini Plug Chanting Machine Box for Pooja Room", "item_url": "https://m.media-amazon.com/images/I/61CBIqOgLwL._AC_UL320_ML3_.jpg", "item_price": "299"},
  {"item_name": "The Four Vedas Mantras Digital Audio CD", "item_url": "https://m.media-amazon.com/images/I/910fVVoRWLL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Shrimad Bhagwat Geeta: Religion Books  (1) (Gujarati Edition)", "item_url": "https://m.media-amazon.com/images/I/71MdPaStTRL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Krishna / Krsna Supreme Personality of Godhead in Telugu - Hard Bound by HDG A.C. Bhaktivedanta Swami Prabhupada", "item_url": "https://m.media-amazon.com/images/I/A1LxgeyJmvL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Bhagavad-Gita As it is  (Tamil) World Most Read Edition", "item_url": "https://m.media-amazon.com/images/I/A1O706YyDmL._AC_UL320_ML3_.jpg", "item_price": "178"},
  {"item_name": "Bhagavad Gita According to Gandhi: Collector's Edition - Gilded and Hardbound - Original Unabridged Translation of the Sanskrit Text by Mahatma Gandhi (Quignog Collectibles)", "item_url": "https://m.media-amazon.com/images/I/71FVx7Y+i1L._AC_UL320_ML3_.jpg", "item_price": "299"},
  {"item_name": "I Jewels Traditional Gold Plated Kundan Pearl Choker Necklace Set Earrings & Maang Tikka for Women (IJ325G)", "item_url": "https://m.media-amazon.com/images/I/71o1mBei1hL._AC_UL320_ML3_.jpg", "item_price": "1,105"},
  {"item_name": "VRINDAVANBAZAAR Liquid Chandan Gopi Tilak (White)", "item_url": "https://m.media-amazon.com/images/I/41XwBMCuF5L._AC_UL320_ML3_.jpg", "item_price": "110"},
  {"item_name": "Radha Krishna Wall Hanging |Radha Krishna Jhula Wall Hanging for Home Decor", "item_url": "https://m.media-amazon.com/images/I/71TmSRkmAEL._AC_UL320_ML3_.jpg", "item_price": "799"},
  {"item_name": "Fabzone Brown Antique Look Lord Ganesha God OM Ganesh Ganpati Idol Statue Wall Hanging Showpiece Figurine", "item_url": "https://m.media-amazon.com/images/I/71d8VOc22PL._AC_UL320_ML3_.jpg", "item_price": "599"},
  {"item_name": "Crafthut Handmade Brass Material Statue of Lord Radha Krishna Seating on Jhoola/Swing", "item_url": "https://m.media-amazon.com/images/I/71rHTeqk2AL._AC_UL320_ML3_.jpg", "item_price": "1,499"},
  {"item_name": "ISKCON Jagannath Tulsi Bead Triple Layer Kanthi Mala for Neck", "item_url": "https://m.media-amazon.com/images/I/91qX4o7A5lL._AC_UL320_ML3_.jpg", "item_price": "198"},
  {"item_name": "Krsna Pastimes Colouring Book", "item_url": "https://m.media-amazon.com/images/I/51jXgv4NSIL._AC_UL320_ML3_.jpg", "item_price": "165"},
  {"item_name": "Life's Amazing Secrets (Hindi): Jeevan Ke Adbhut Rahasya", "item_url": "https://m.media-amazon.com/images/I/71c96eeGwjL._AC_UL320_ML3_.jpg", "item_price": "97"},
  {"item_name": "Bhagavad Gita As It Is Macmillan-Original Edition", "item_url": "https://m.media-amazon.com/images/I/81raGIB2zLL._AC_UL320_ML3_.jpg", "item_price": "255"},
  {"item_name": "A Comprehensive Guide to Bhagavad-Gita with Literal Translation", "item_url": "https://m.media-amazon.com/images/I/71ZUJA9lepL._AC_UL320_ML3_.jpg", "item_price": "490"},
  {"item_name": "ISKCON Jagannath Bbt Murali Krishna Fine Art Print Poster (Paper, Multicolour)", "item_url": "https://m.media-amazon.com/images/I/61Y5-PgkdGL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath Certified Copper or Tamba Ring Adjustable and Flexible Size for Men and Women", "item_url": "https://m.media-amazon.com/images/I/61C4hI37+rL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath 1 Round Multicolour Wooden Bead Single Layer Kanthi Mala Necklace (43.18 cm)", "item_url": "https://m.media-amazon.com/images/I/61-oPNjQOwL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "The Bhagavad Gita: Chapters 1-13", "item_url": "https://m.media-amazon.com/images/I/713GvsYZGsL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Bhagavad-Gita (Hindi)", "item_url": "https://m.media-amazon.com/images/I/71sEb27W4rL._AC_UL320_ML3_.jpg", "item_price": "122"},
  {"item_name": "ISKCON Jagannath Bhagavad-Gita As It is Telugu Hardcover (0.5 x 5.4 x 8.4cm, Multicolour)", "item_url": "https://m.media-amazon.com/images/I/71lKUGZPQtL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath Dashavatara Fine Art Paper Print Poster", "item_url": "https://m.media-amazon.com/images/I/612AqGdJ+2L._AC_UL320_ML3_.jpg", "item_price": "108"},
  ];
List cat2 = [
  {"item_name": "In Vaikuntha Not Even The Leaves Fall: A Treatise On The Bondage Of The Jiva", "item_url": "https://m.media-amazon.com/images/I/71nyvDru6EL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Arcana, Volume 2: The ISKCON Deity Worship Journal", "item_url": "https://m.media-amazon.com/images/I/81jNGxJW9YL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Lord krishna's 46 in 1 Gayatri Mantra Hare Krishna (Iskcon Voice) Mini Plug Chanting Machine Box for Pooja Room", "item_url": "https://m.media-amazon.com/images/I/61CBIqOgLwL._AC_UL320_ML3_.jpg", "item_price": "299"},
  {"item_name": "The Four Vedas Mantras Digital Audio CD", "item_url": "https://m.media-amazon.com/images/I/910fVVoRWLL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "bhagavad gita (oriya)", "item_url": "https://m.media-amazon.com/images/I/61yNGq7tWoL._AC_UL320_ML3_.jpg", "item_price": "295"},
  {"item_name": "ALCiS Men's Round Neck Synthetic T-Shirt", "item_url": "https://m.media-amazon.com/images/I/81IdDHpUMGL._AC_UL320_ML3_.jpg", "item_price": "279"},
  {"item_name": "ISKCON Jagannath Krishna Dances over Kaliya Snake Hood Fine Art Paper Print Poster (Multicolour, 19.5 x 13.5 inches)", "item_url": "https://m.media-amazon.com/images/I/71VRGAa0wGL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Kingston 8 GB microSDHC Class 4 Flash Memory Card SDC4/8GB CO8G Taiwan", "item_url": "https://m.media-amazon.com/images/I/61qcFt4D2SL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Reflections on Sacred Teachings IV: Sri Isopanisad", "item_url": "https://m.media-amazon.com/images/I/51RvI7m+K2L._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Valmiki Ramayanam", "item_url": "https://m.media-amazon.com/images/I/71e1hUBbr6L._AC_UL320_ML3_.jpg", "item_price": "250"},
  {"item_name": "God Talks with Arjuna: The Bhagavad Gita (Slipcased)", "item_url": "https://m.media-amazon.com/images/I/51N5ghz0izL._AC_UL320_ML3_.jpg", "item_price": "605"},
  {"item_name": "Bhagavad-gita As It Is", "item_url": "https://m.media-amazon.com/images/I/81TXvt0QVeL._AC_UL320_ML3_.jpg", "item_price": "257"},
  {"item_name": "Ramayana of Valmiki-English Edition Paperback \u2013 2014", "item_url": "https://m.media-amazon.com/images/I/41509vgMNbL._AC_UL320_ML3_.jpg", "item_price": "165"},
  {"item_name": "KRISHNA:Devadi_Devudu Sri Krishna Bhagavanudu (Hardcover, Telugu, His Divine Grace A.C. Bhaktivedanta Swami Prabhupada)", "item_url": "https://m.media-amazon.com/images/I/513sosXGijL._AC_UL320_ML3_.jpg", "item_price": "349"},
  {"item_name": "Bhagavad Gita As It is Hindi by His Divine Grace A.C.Bhaktivedanta Swami Srila Prabhupada", "item_url": "https://m.media-amazon.com/images/I/51esXLpRisL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Krsna Pastimes Colouring Book", "item_url": "https://m.media-amazon.com/images/I/51jXgv4NSIL._AC_UL320_ML3_.jpg", "item_price": "165"},
  {"item_name": "Original Bhagavad Gita (Small Size) \u2014 Dual Color Print", "item_url": "https://m.media-amazon.com/images/I/81FC5v9M0jL._AC_UL320_ML3_.jpg", "item_price": "399"},
  {"item_name": "Shrimad Bhagwat Geeta: Religion Books  (1) (Gujarati Edition)", "item_url": "https://m.media-amazon.com/images/I/71MdPaStTRL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Prabhupada: Messenger of the Supreme Lord [Biography of Srila Prabhupada, the founder Acarya of ISKCON]", "item_url": "https://m.media-amazon.com/images/I/51pjwZedJ4L._AC_UL320_ML3_.jpg", "item_price": "130"},
  {"item_name": "Sai Amrut Antique Marble Finish Lord Radha Krishna Statue/Idol 7inch", "item_url": "https://m.media-amazon.com/images/I/81WHZmeDwaL._AC_UL320_ML3_.jpg", "item_price": "899"},
  {"item_name": "ISKCON Jagannath Red Silver Plated Lord Jagannath Pendant/Locket for Men and Women", "item_url": "https://m.media-amazon.com/images/I/41QqC+CcTNL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Krishna Playing Flute Fun Spring -VRINDAVANBAZAAR.COM", "item_url": "https://m.media-amazon.com/images/I/61iriQYOQvL._AC_UL320_ML3_.jpg", "item_price": "200"},
  {"item_name": "Lord krishna's Plastic 46in1 Gayatri Mantra Chanting Box Machine Music Box", "item_url": "https://m.media-amazon.com/images/I/61foqIlQtoL._AC_UL320_ML3_.jpg", "item_price": "399"},
  {"item_name": "God's Own Kitchen: The Inspiring Story of Akshaya Patra - A Social Enterprise Run by Monks and CEOs", "item_url": "https://m.media-amazon.com/images/I/51Mp1nshX9L._AC_UL320_ML3_.jpg", "item_price": "207"},
  {"item_name": "Gauranga - The golden incarnation of divine love", "item_url": "https://m.media-amazon.com/images/I/51zC3op0HgL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Swami in a Strange Land: How Krishna Came to the West", "item_url": "https://m.media-amazon.com/images/I/71Yg566N5sL._AC_UL320_ML3_.jpg", "item_price": "333"},
  {"item_name": "The Teaching of the Bhagavad Gita", "item_url": "https://m.media-amazon.com/images/I/8179cCxWCcL._AC_UL320_ML3_.jpg", "item_price": "224"},
  {"item_name": "My Gita", "item_url": "https://m.media-amazon.com/images/I/71R1VMOZr8L._AC_UL320_ML3_.jpg", "item_price": "168"},
  {"item_name": "ISKCON Jagannath Bbt Murali Krishna Fine Art Print Poster (Paper, Multicolour)", "item_url": "https://m.media-amazon.com/images/I/61Y5-PgkdGL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Kingston 8 GB microSDHC Class 4 Flash Memory Card SDC4/8GB CO8G Taiwan", "item_url": "https://m.media-amazon.com/images/I/61qcFt4D2SL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ALCiS Women's Asymmetric Vest Top", "item_url": "https://m.media-amazon.com/images/I/813kBAsfQLL._AC_UL320_ML3_.jpg", "item_price": "251"},
  {"item_name": "ISKCON Jagannath Krishna Dances over Kaliya Snake Hood Fine Art Paper Print Poster (Multicolour, 19.5 x 13.5 inches)", "item_url": "https://m.media-amazon.com/images/I/71VRGAa0wGL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Life's Amazing Secrets (Hindi): Jeevan Ke Adbhut Rahasya", "item_url": "https://m.media-amazon.com/images/I/71c96eeGwjL._AC_UL320_ML3_.jpg", "item_price": "97"},
  {"item_name": "Bhagavad Gita As It Is Macmillan-Original Edition", "item_url": "https://m.media-amazon.com/images/I/81raGIB2zLL._AC_UL320_ML3_.jpg", "item_price": "255"},
  {"item_name": "Easy Journey to Other Planets", "item_url": "https://m.media-amazon.com/images/I/51Y5R51TDYL._AC_UL320_ML3_.jpg", "item_price": "64"},
  {"item_name": "Bhagavad Gita As It Is -Pocket Size", "item_url": "https://m.media-amazon.com/images/I/81qwP0egX4L._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "The Scientific Basis", "item_url": "https://m.media-amazon.com/images/I/811XYk7ZO9L._AC_UL320_ML3_.jpg", "item_price": "110"},
  {"item_name": "Sri Namastaka of Srila Rupa Gosvami Prabhupada", "item_url": "https://m.media-amazon.com/images/I/91mYBtca7ML._AC_UL320_ML3_.jpg", "item_price": "150"},
  {"item_name": "A Beginner's Guide to Krishna Consciousness", "item_url": "https://m.media-amazon.com/images/I/91uZrMiutPL._AC_UL320_ML3_.jpg", "item_price": "108"},
  ];
List cat3 = [
  {"item_name": "Krishna, The Reservoir of Pleasure", "item_url": "https://m.media-amazon.com/images/I/51-mzzx0H5L._AC_UL320_ML3_.jpg", "item_price": "51"},
  {"item_name": "Arcana, Volume 1: The ISKCON Deity Worship Journal", "item_url": "https://m.media-amazon.com/images/I/81JKREQtRTL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "The Final Order: Proves Srila Prabhupada is ISKCON's Initiating Guru", "item_url": "https://m.media-amazon.com/images/I/9166l7++VSL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "ISKCON Jagannath Multicolour Tulsi Beads Triple Layer Kanthi Mala/Necklace", "item_url": "https://m.media-amazon.com/images/I/71NI1IMfOqL._AC_UL320_ML3_.jpg", "item_price": "195"},
  {"item_name": "Bhagavad-Gita As it is (Telugu)", "item_url": "https://m.media-amazon.com/images/I/718fZcBNKlL._AC_UL320_ML3_.jpg", "item_price": "200"},
  {"item_name": "Bhagavad Gita - Pure: A Comprehensive Study without Sectarian Contamination", "item_url": "https://m.media-amazon.com/images/I/71KIjx2gmML._AC_UL320_ML3_.jpg", "item_price": "51"},
  {"item_name": "ISKCON Jagannath Cotton Thread/Mouli/Lal Dhaga for Puja (Red) -1 Roll", "item_url": "https://m.media-amazon.com/images/I/31UtCeqS5EL._AC_UL320_ML3_.jpg", "item_price": "80"},
  {"item_name": "A Comprehensive Guide to Bhagavad-Gita with Literal Translation", "item_url": "https://m.media-amazon.com/images/I/71ZUJA9lepL._AC_UL320_ML3_.jpg", "item_price": "490"},
  {"item_name": "ISKCON Jagannath Certified Copper or Tamba Ring Adjustable and Flexible Size for Men and Women", "item_url": "https://m.media-amazon.com/images/I/61C4hI37+rL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "bhagavad gita (oriya)", "item_url": "https://m.media-amazon.com/images/I/61yNGq7tWoL._AC_UL320_ML3_.jpg", "item_price": "295"},
  {"item_name": "Reflections on Sacred Teachings IV: Sri Isopanisad", "item_url": "https://m.media-amazon.com/images/I/51RvI7m+K2L._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Krishna Playing Flute Fun Spring -VRINDAVANBAZAAR.COM", "item_url": "https://m.media-amazon.com/images/I/61iriQYOQvL._AC_UL320_ML3_.jpg", "item_price": "200"},
  {"item_name": "Lord krishna's Marathi 22 in 1 Digambara Digambara/Shree Swami Samarth/Gayatri Mantra/Maha Mantra (Iskcon Voice) Mini Plug Device Chanting Machine Box for Pooja Room", "item_url": "https://m.media-amazon.com/images/I/61pg6MXTRBL._AC_UL320_ML3_.jpg", "item_price": "219"},
  {"item_name": "ISKCON Jagannath Divine Kala Black Moti for Men and Women", "item_url": "https://m.media-amazon.com/images/I/71KZqj5RSAL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Bhagavad gita : Bio-Science and Psychology (Volume 2)", "item_url": "https://m.media-amazon.com/images/I/61n8nGy+gWL._AC_UL320_ML3_.jpg", "item_price": "499"},
  {"item_name": "ALCiS Men's Round Neck Synthetic T-Shirt", "item_url": "https://m.media-amazon.com/images/I/81F8ywJjy5L._AC_UL320_ML3_.jpg", "item_price": "387"},
  {"item_name": "Lord krishna's Plastic 46in1 Gayatri Mantra Chanting Box Machine Music Box", "item_url": "https://m.media-amazon.com/images/I/61foqIlQtoL._AC_UL320_ML3_.jpg", "item_price": "399"},
  {"item_name": "Bhagavad Gita As It Is Macmillan-Original Edition", "item_url": "https://m.media-amazon.com/images/I/81raGIB2zLL._AC_UL320_ML3_.jpg", "item_price": "255"},
  {"item_name": "Murali Krishna Blue Colour Deity/Statue / Murti/Idol", "item_url": "https://m.media-amazon.com/images/I/61OUrfbFNAL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "AEON METAL STICKER 3D Plastic Night Lamp, Multicolour", "item_url": "https://m.media-amazon.com/images/I/81mw592F07L._AC_UL320_ML3_.jpg", "item_price": "299"},
  {"item_name": "Bhagavad Gita (A handbook for Students)", "item_url": "https://m.media-amazon.com/images/I/81ugvFGQUoL._AC_UL320_ML3_.jpg", "item_price": "90"},
  {"item_name": "Lord krishna's Plastic 46in1 Gayatri Mantra Chanting Box Machine Music Box", "item_url": "https://m.media-amazon.com/images/I/61foqIlQtoL._AC_UL320_ML3_.jpg", "item_price": "399"},
  {"item_name": "Valmiki Ramayanam", "item_url": "https://m.media-amazon.com/images/I/71e1hUBbr6L._AC_UL320_ML3_.jpg", "item_price": "250"},
  {"item_name": "ISKCON Jagannath Yellow Silver Plated Pendant/Locket for Men and Women", "item_url": "https://m.media-amazon.com/images/I/41Tu01M8apL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ALCiS Women's Asymmetric Vest Top", "item_url": "https://m.media-amazon.com/images/I/81ZYHPtGruL._AC_UL320_ML3_.jpg", "item_price": "216"},
  {"item_name": "Lord krishna's Marathi 22 in 1 Digambara Digambara/Shree Swami Samarth/Gayatri Mantra/Maha Mantra (Iskcon Voice) Mini Plug Device Chanting Machine Box for Pooja Room", "item_url": "https://m.media-amazon.com/images/I/61pg6MXTRBL._AC_UL320_ML3_.jpg", "item_price": "219"},
  {"item_name": "God's Own Kitchen: The Inspiring Story of Akshaya Patra - A Social Enterprise Run by Monks and CEOs", "item_url": "https://m.media-amazon.com/images/I/51Mp1nshX9L._AC_UL320_ML3_.jpg", "item_price": "207"},
  {"item_name": "ISKCON Jagannath Fine Art Krishna with Balaram and Captivates Gopis Poster (Paper, 19.5 x 13.5 inches, Multicolour)", "item_url": "https://m.media-amazon.com/images/I/419nMFbFM5L._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Spiritual Warrior I: Uncovering Spiritual Truths in Psychic Phenomena", "item_url": "https://m.media-amazon.com/images/I/510F-ydbJtL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Om Namah Shivaya Digital Audio CD", "item_url": "https://m.media-amazon.com/images/I/91wvF7fhjTL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath Silver Plated Tulsi/Tulasi Kanthi Mala for Men and Women", "item_url": "https://m.media-amazon.com/images/I/81gBm14fNlL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Abloom 108 Beads Iskcon Wood Unisex Tulsi Jaap Mala for Wearing", "item_url": "https://m.media-amazon.com/images/I/613OyG3IsAL._AC_UL320_ML3_.jpg", "item_price": "339"},
  {"item_name": "ALCiS Men's Round Neck Cotton T-Shirt", "item_url": "https://m.media-amazon.com/images/I/81Zf0lgPunL._AC_UL320_ML3_.jpg", "item_price": "279"},
  {"item_name": "Original Bhagavad Gita (Small Size) \u2014 Dual Color Print", "item_url": "https://m.media-amazon.com/images/I/81FC5v9M0jL._AC_UL320_ML3_.jpg", "item_price": "399"},
  {"item_name": "What is the difficulty?: Intimate Monents in the Personal Service of His Divine Grace A.C. Bhaktivedanta Swami Prabhupada", "item_url": "https://m.media-amazon.com/images/I/81pzfbHhntL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "ISKCON BBT KRISHNA GIRI GOVERDHAN FINE ART PAPER PRINT POSTER", "item_url": "https://m.media-amazon.com/images/I/614rXT1bOKL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Surrender: The Key to Eternal Life", "item_url": "https://m.media-amazon.com/images/I/71KKdE+ZF-L._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Bhagavad Gita As It is English by His Divine Grace A.C.Bhaktivedanta Swami Prabhupada", "item_url": "https://m.media-amazon.com/images/I/51t0IecmHVL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath Fine Art Krishna with Balaram and Captivates Gopis Poster (Paper, 19.5 x 13.5 inches, Multicolour)", "item_url": "https://m.media-amazon.com/images/I/419nMFbFM5L._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Gauranga - The golden incarnation of divine love", "item_url": "https://m.media-amazon.com/images/I/51zC3op0HgL._AC_UL320_ML3_.jpg", "item_price": "0"},
  ];
List cat4 = [
  {"item_name": "Easy Journey to Other Planets", "item_url": "https://m.media-amazon.com/images/I/51Y5R51TDYL._AC_UL320_ML3_.jpg", "item_price": "64"},
  {"item_name": "Bhagavad Gita As It Is -Pocket Size", "item_url": "https://m.media-amazon.com/images/I/81qwP0egX4L._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "The Scientific Basis", "item_url": "https://m.media-amazon.com/images/I/811XYk7ZO9L._AC_UL320_ML3_.jpg", "item_price": "110"},
  {"item_name": "Bhagavad Gita As It Is (Marathi)", "item_url": "https://m.media-amazon.com/images/I/51QmtclhbbL._AC_UL320_ML3_.jpg", "item_price": "140"},
  {"item_name": "Journey Through The Bhagavad Gita - A Modern Commentary With Word-To-Word Sanskrit-English Translation", "item_url": "https://m.media-amazon.com/images/I/61gOL3FKHcL._AC_UL320_ML3_.jpg", "item_price": "3,710"},
  {"item_name": "Lord krishna's Marathi 22 in 1 Digambara Digambara/Shree Swami Samarth/Gayatri Mantra/Maha Mantra (Iskcon) Mini Plug Device Chanting Machine Box for Pooja Room", "item_url": "https://m.media-amazon.com/images/I/61pg6MXTRBL._AC_UL320_ML3_.jpg", "item_price": "219"},
  {"item_name": "Krishna with cow in Antique golden finish by Handicrafts Paradise", "item_url": "https://m.media-amazon.com/images/I/61ySSL8fcaL._AC_UL320_ML3_.jpg", "item_price": "325"},
  {"item_name": "BHAGAVAD GITA ( BENGALI ) (2016 New Edition) -ISKCON \"BEST SELLER\" -Self Help-Greatest...", "item_url": "https://m.media-amazon.com/images/I/51Jjy5NzGiL._AC_UL320_ML3_.jpg", "item_price": "350"},
  {"item_name": "The Bhagavad Gita", "item_url": "https://m.media-amazon.com/images/I/71AwuAgQp2L._AC_UL320_ML3_.jpg", "item_price": "199"},
  {"item_name": "The Scientific Basis", "item_url": "https://m.media-amazon.com/images/I/811XYk7ZO9L._AC_UL320_ML3_.jpg", "item_price": "110"},
  {"item_name": "ISKCON BBT RADHA KRISHNA (RADHA RASBIHARI) FINE ART PAPER PRINT POSTER", "item_url": "https://m.media-amazon.com/images/I/A1zioJ0wIzL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath Metal Lord Shree Krishna Pendant for Men and Women", "item_url": "https://m.media-amazon.com/images/I/518CSiugatL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath Bhagavad-Gita As It is Telugu Hardcover (0.5 x 5.4 x 8.4cm, Multicolour)", "item_url": "https://m.media-amazon.com/images/I/71lKUGZPQtL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Sri Namastaka of Srila Rupa Gosvami Prabhupada", "item_url": "https://m.media-amazon.com/images/I/91mYBtca7ML._AC_UL320_ML3_.jpg", "item_price": "150"},
  {"item_name": "A Beginner's Guide to Krishna Consciousness", "item_url": "https://m.media-amazon.com/images/I/91uZrMiutPL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Krishna, The Reservoir of Pleasure", "item_url": "https://m.media-amazon.com/images/I/51-mzzx0H5L._AC_UL320_ML3_.jpg", "item_price": "51"},
  {"item_name": "Lord krishna's Marathi 22 in 1 Digambara Digambara/Shree Swami Samarth/Gayatri Mantra/Maha Mantra (Iskcon) Mini Plug Device Chanting Machine Box for Pooja Room", "item_url": "https://m.media-amazon.com/images/I/61pg6MXTRBL._AC_UL320_ML3_.jpg", "item_price": "219"},
  {"item_name": "TRUSTFUL Brass Handmade Wall Hanging Surya Chakra Ganesh Idol for Home Decorative", "item_url": "https://m.media-amazon.com/images/I/61vLVeFUuHL._AC_UL320_ML3_.jpg", "item_price": "499"},
  {"item_name": "Srila Prabhupada: The Founder-Acarya of ISKCON", "item_url": "https://m.media-amazon.com/images/I/81jnVbvIM2L._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "The Journey Home: Autobiography of an American Swami", "item_url": "https://m.media-amazon.com/images/I/718A5ClfIdL._AC_UL320_ML3_.jpg", "item_price": "302"},
  {"item_name": "ISKCON BBT JAGANNATH BALADEVA SUBHADRA DEITY FINE ART PAPER PRINT POSTER", "item_url": "https://m.media-amazon.com/images/I/A1I3x3wrGvL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ALCiS Men's Round Neck Synthetic T-Shirt", "item_url": "https://m.media-amazon.com/images/I/81R-+2tS8-L._AC_UL320_ML3_.jpg", "item_price": "369"},
  {"item_name": "Bhagavad Gita As It Is (Kannada)- World Most Read Edition", "item_url": "https://m.media-amazon.com/images/I/51pXegIKBpL._AC_UL320_ML3_.jpg", "item_price": "294"},
  {"item_name": "AEON METAL STICKER 3D Plastic Night Lamp, Multicolour", "item_url": "https://m.media-amazon.com/images/I/81mw592F07L._AC_UL320_ML3_.jpg", "item_price": "299"},
  {"item_name": "ISKCON Jagannath Red Silver Plated Lord Jagannath Pendant/Locket for Men and Women", "item_url": "https://m.media-amazon.com/images/I/41QqC+CcTNL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Bhagavad gita : Bio-Science and Psychology (Volume 2)", "item_url": "https://m.media-amazon.com/images/I/61n8nGy+gWL._AC_UL320_ML3_.jpg", "item_price": "499"},
  {"item_name": "Om Namah Shivaya Digital Audio CD", "item_url": "https://m.media-amazon.com/images/I/91wvF7fhjTL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Sai Amrut Antique Marble Finish Lord Radha Krishna Statue/Idol 7inch", "item_url": "https://m.media-amazon.com/images/I/81WHZmeDwaL._AC_UL320_ML3_.jpg", "item_price": "899"},
  {"item_name": "Spiritual Warrior I: Uncovering Spiritual Truths in Psychic Phenomena", "item_url": "https://m.media-amazon.com/images/I/510F-ydbJtL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Srila Prabhupada Lilamrta: Biography of Srila Prabhupada (Founder Acarya of ISKCON)- 7 Vols. Set", "item_url": "https://m.media-amazon.com/images/I/61IR1YTWorL._AC_UL320_ML3_.jpg", "item_price": "1,800"},
  {"item_name": "ISKCON BBT MURALI KRISHNA FINE ART PAPER PRINT POSTER", "item_url": "https://m.media-amazon.com/images/I/61TaicagqnL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "100 Contradictions: The Life & Teachings of His Holiness Bhakti Charu Swami", "item_url": "https://m.media-amazon.com/images/I/81CwrmZNefL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "ISKCON Jagannath JAAP MALA for Pooja-Astrology-108+1 Beads and Certified Small Size", "item_url": "https://m.media-amazon.com/images/I/41XLJJ9XKsL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Kitchen Tools of Sev Sancha/idiyappam/murukku/sev Maker Machine/chakli/Kitchen Press Stainless Steel Different Type of jalis", "item_url": "https://m.media-amazon.com/images/I/415BSY0hB-L._AC_UL320_ML3_.jpg", "item_price": "346"},
  {"item_name": "ALCiS Men's Round Neck Synthetic T-Shirt", "item_url": "https://m.media-amazon.com/images/I/81IdDHpUMGL._AC_UL320_ML3_.jpg", "item_price": "279"},
  {"item_name": "ISKCON Jagannath, Balaram and Subhadra (Stone Statue) No 4B Stand 2.75 x 4.5 x 1 inches", "item_url": "https://m.media-amazon.com/images/I/81mUarwr7ML._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Krishna with cow in Antique golden finish by Handicrafts Paradise", "item_url": "https://m.media-amazon.com/images/I/61ySSL8fcaL._AC_UL320_ML3_.jpg", "item_price": "325"},
  {"item_name": "TRUSTFUL Brass Handmade Wall Hanging Surya Chakra Ganesh Idol for Home Decorative", "item_url": "https://m.media-amazon.com/images/I/61vLVeFUuHL._AC_UL320_ML3_.jpg", "item_price": "499"},
  {"item_name": "Gita According to Gandhi (General Press)", "item_url": "https://m.media-amazon.com/images/I/71VN-LvgOOL._AC_UL320_ML3_.jpg", "item_price": "156"},
  {"item_name": "Krishna with cow in Antique golden finish by Handicrafts Paradise", "item_url": "https://m.media-amazon.com/images/I/61ySSL8fcaL._AC_UL320_ML3_.jpg", "item_price": "325"},
  {"item_name": "TRUSTFUL Brass Handmade Wall Hanging Surya Chakra Ganesh Idol for Home Decorative", "item_url": "https://m.media-amazon.com/images/I/61vLVeFUuHL._AC_UL320_ML3_.jpg", "item_price": "499"},
  {"item_name": "Radha Krishna Wall Hanging |Radha Krishna Jhula Wall Hanging for Home Decor", "item_url": "https://m.media-amazon.com/images/I/71TmSRkmAEL._AC_UL320_ML3_.jpg", "item_price": "799"},
  {"item_name": "Fabzone Brown Antique Look Lord Ganesha God OM Ganesh Ganpati Idol Statue Wall Hanging Showpiece Figurine", "item_url": "https://m.media-amazon.com/images/I/71d8VOc22PL._AC_UL320_ML3_.jpg", "item_price": "599"},
  {"item_name": "Crafthut Handmade Brass Material Statue of Lord Radha Krishna Seating on Jhoola/Swing", "item_url": "https://m.media-amazon.com/images/I/71rHTeqk2AL._AC_UL320_ML3_.jpg", "item_price": "1,499"},
  ];
List cat5= [
  {"item_name": "The Nectar of Instruction", "item_url": "https://m.media-amazon.com/images/I/81GM0OodKHL._AC_UL320_ML3_.jpg", "item_price": "70"},
  {"item_name": "Bhagavad Gita As It Is Macmillan-Original Edition", "item_url": "https://m.media-amazon.com/images/I/81raGIB2zLL._AC_UL320_ML3_.jpg", "item_price": "255"},
  {"item_name": "ISKCON Rudraksha 5 Mukhi RUDRAKSHA JAAP MALA / BEADS FOR POOJA (ASTROLOGY) (108+1 Beads) 100% Original and Certified", "item_url": "https://m.media-amazon.com/images/I/41fLbHcYqJL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ALCiS Women's Asymmetric Vest Top", "item_url": "https://m.media-amazon.com/images/I/81ZYHPtGruL._AC_UL320_ML3_.jpg", "item_price": "216"},
  {"item_name": "Bhagavad Gita As It is Hindi by His Divine Grace A.C.Bhaktivedanta Swami Srila Prabhupada", "item_url": "https://m.media-amazon.com/images/I/51esXLpRisL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath JAAP MALA for Pooja-Astrology-108+1 Beads and Certified Small Size", "item_url": "https://m.media-amazon.com/images/I/41XLJJ9XKsL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Gita According to Gandhi (General Press)", "item_url": "https://m.media-amazon.com/images/I/71VN-LvgOOL._AC_UL320_ML3_.jpg", "item_price": "156"},
  {"item_name": "Sri Namastaka of Srila Rupa Gosvami Prabhupada", "item_url": "https://m.media-amazon.com/images/I/91mYBtca7ML._AC_UL320_ML3_.jpg", "item_price": "150"},
  {"item_name": "What is the difficulty?: Intimate Monents in the Personal Service of His Divine Grace A.C. Bhaktivedanta Swami Prabhupada", "item_url": "https://m.media-amazon.com/images/I/81pzfbHhntL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "ISKCON Jagannath Dashavatara Fine Art Paper Print Poster", "item_url": "https://m.media-amazon.com/images/I/612AqGdJ+2L._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "The Four Vedas Mantras Digital Audio CD", "item_url": "https://m.media-amazon.com/images/I/910fVVoRWLL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath Yellow Silver Plated Pendant/Locket for Men and Women", "item_url": "https://m.media-amazon.com/images/I/41Tu01M8apL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Lord krishna's 46 in 1 Gayatri Mantra Hare Krishna (Iskcon Voice) Mini Plug Chanting Machine Box for Pooja Room", "item_url": "https://m.media-amazon.com/images/I/61CBIqOgLwL._AC_UL320_ML3_.jpg", "item_price": "299"},
  {"item_name": "Life's Amazing Secrets (Hindi): Jeevan Ke Adbhut Rahasya", "item_url": "https://m.media-amazon.com/images/I/71c96eeGwjL._AC_UL320_ML3_.jpg", "item_price": "97"},
  {"item_name": "The Bhagavad Gita", "item_url": "https://m.media-amazon.com/images/I/91atqshFQnL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "ISKCON Jagannath Tulsi Bead Triple Layer Kanthi Mala for Neck", "item_url": "https://m.media-amazon.com/images/I/91qX4o7A5lL._AC_UL320_ML3_.jpg", "item_price": "198"},
  {"item_name": "bhagavad gita (oriya)", "item_url": "https://m.media-amazon.com/images/I/61yNGq7tWoL._AC_UL320_ML3_.jpg", "item_price": "295"},
  {"item_name": "Krsna Pastimes Colouring Book", "item_url": "https://m.media-amazon.com/images/I/51jXgv4NSIL._AC_UL320_ML3_.jpg", "item_price": "165"},
  {"item_name": "ISKCON Jagannath Metal Lord Shree Krishna Pendant for Men and Women", "item_url": "https://m.media-amazon.com/images/I/518CSiugatL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath Bbt Murali Krishna Fine Art Print Poster (Paper, Multicolour)", "item_url": "https://m.media-amazon.com/images/I/61Y5-PgkdGL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Arcana, Volume 4: The ISKCON Deity Worship Journal", "item_url": "https://m.media-amazon.com/images/I/71f2Zz8PdwL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "Valmiki Ramayanam", "item_url": "https://m.media-amazon.com/images/I/71e1hUBbr6L._AC_UL320_ML3_.jpg", "item_price": "250"},
  {"item_name": "The Scientific Basis", "item_url": "https://m.media-amazon.com/images/I/811XYk7ZO9L._AC_UL320_ML3_.jpg", "item_price": "110"},
  {"item_name": "ISKCON Jagannath Krishna Dances over Kaliya Snake Hood Fine Art Paper Print Poster (Multicolour, 19.5 x 13.5 inches)", "item_url": "https://m.media-amazon.com/images/I/71VRGAa0wGL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ALCiS Men's Round Neck Synthetic T-Shirt", "item_url": "https://m.media-amazon.com/images/I/81IdDHpUMGL._AC_UL320_ML3_.jpg", "item_price": "279"},
  {"item_name": "ISKCON Jagannath Certified Copper or Tamba Ring Adjustable and Flexible Size for Men and Women", "item_url": "https://m.media-amazon.com/images/I/61C4hI37+rL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Arcana, Volume 3: The ISKCON Deity Worship Journal", "item_url": "https://m.media-amazon.com/images/I/81rZ4Fbv+bL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "The Bhagavad Gita (Hardcover Library Edition)", "item_url": "https://m.media-amazon.com/images/I/71T4Lx7KcZL._AC_UL320_ML3_.jpg", "item_price": "184"},
  {"item_name": "A Beginner's Guide to Krishna Consciousness", "item_url": "https://m.media-amazon.com/images/I/91uZrMiutPL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Bhagavad gita : Bio-Science and Psychology (Volume 2)", "item_url": "https://m.media-amazon.com/images/I/61n8nGy+gWL._AC_UL320_ML3_.jpg", "item_price": "499"},
  {"item_name": "Bhakti: The Art of Eternal Love", "item_url": "https://m.media-amazon.com/images/I/61M7e+GtdhL._AC_UL320_ML3_.jpg", "item_price": "110"},
  {"item_name": "Krsna Karnamrta", "item_url": "https://m.media-amazon.com/images/I/51wb9kjS3eL._AC_UL320_ML3_.jpg", "item_price": "270"},
  {"item_name": "Krishna Playing Flute Fun Spring -VRINDAVANBAZAAR.COM", "item_url": "https://m.media-amazon.com/images/I/61iriQYOQvL._AC_UL320_ML3_.jpg", "item_price": "200"},
  {"item_name": "Om Namah Shivaya Digital Audio CD", "item_url": "https://m.media-amazon.com/images/I/91wvF7fhjTL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "Sai Amrut Antique Marble Finish Lord Radha Krishna Statue/Idol 7inch", "item_url": "https://m.media-amazon.com/images/I/81WHZmeDwaL._AC_UL320_ML3_.jpg", "item_price": "899"},
  {"item_name": "La Derni\u00e8re Directive: Etablit que Srila Prabhupada est le ma\u00eetre spirituel donnant l\u2019initiation dans ISKCON (French Edition)", "item_url": "https://m.media-amazon.com/images/I/81q4zW7gMUL._AC_UL320_ML3_.jpg", "item_price": "0"},
  {"item_name": "ISKCON Jagannath Red Silver Plated Lord Jagannath Pendant/Locket for Men and Women", "item_url": "https://m.media-amazon.com/images/I/41QqC+CcTNL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "The Wisdom of the Gita: A Manual for Life", "item_url": "https://m.media-amazon.com/images/I/71i-T9nuI7L._AC_UL320_ML3_.jpg", "item_price": "103"},
  {"item_name": "ALCiS Men's Round Neck Synthetic T-Shirt", "item_url": "https://m.media-amazon.com/images/I/81F8ywJjy5L._AC_UL320_ML3_.jpg", "item_price": "387"},
  {"item_name": "La Order Final: Un ensayo que trata sobre las instrucciones de Srila Prabhupada acerca de las iniciaciones en ISKCON (Spanish Edition)", "item_url": "https://m.media-amazon.com/images/I/91Uulrgpv3L._AC_UL320_ML3_.jpg", "item_price": "49"},
  {"item_name": "Lord krishna's Marathi 22 in 1 Digambara Digambara/Shree Swami Samarth/Gayatri Mantra/Maha Mantra (Iskcon Voice) Mini Plug Device Chanting Machine Box for Pooja Room", "item_url": "https://m.media-amazon.com/images/I/61pg6MXTRBL._AC_UL320_ML3_.jpg", "item_price": "219"},
  {"item_name": "Bhagavad-Gita As it is  (Tamil) World Most Read Edition", "item_url": "https://m.media-amazon.com/images/I/A1O706YyDmL._AC_UL320_ML3_.jpg", "item_price": "178"},
  {"item_name": "In Search of the Ultimate Goal of Life", "item_url": "https://m.media-amazon.com/images/I/91q6VApbMuL._AC_UL320_ML3_.jpg", "item_price": "250"},
  {"item_name": "A Comprehensive Guide to Bhagavad-Gita with Literal Translation", "item_url": "https://m.media-amazon.com/images/I/71ZUJA9lepL._AC_UL320_ML3_.jpg", "item_price": "490"},
  {"item_name": "Srila Prabhupada Lilamrta: Biography of Srila Prabhupada (Founder Acarya of ISKCON)- 7 Vols. Set", "item_url": "https://m.media-amazon.com/images/I/61IR1YTWorL._AC_UL320_ML3_.jpg", "item_price": "1,800"},
  {"item_name": "ISKCON Jagannath Fine Art Krishna with Balaram and Captivates Gopis Poster (Paper, 19.5 x 13.5 inches, Multicolour)", "item_url": "https://m.media-amazon.com/images/I/419nMFbFM5L._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "ISKCON Jagannath Divine Kala Black Moti for Men and Women", "item_url": "https://m.media-amazon.com/images/I/71KZqj5RSAL._AC_UL320_ML3_.jpg", "item_price": "108"},
  {"item_name": "The \u015aik\u1e63\u0101-guru: Implementing Tradition Within ISKCON", "item_url": "https://m.media-amazon.com/images/I/91M-SWUZEAL._AC_UL320_ML3_.jpg", "item_price": "268"},
  {"item_name": "Krishna with cow in Antique golden finish by Handicrafts Paradise", "item_url": "https://m.media-amazon.com/images/I/61ySSL8fcaL._AC_UL320_ML3_.jpg", "item_price": "325"},
  {"item_name": "TRUSTFUL Brass Handmade Wall Hanging Surya Chakra Ganesh Idol for Home Decorative", "item_url": "https://m.media-amazon.com/images/I/61vLVeFUuHL._AC_UL320_ML3_.jpg", "item_price": "499"},
];